---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-postgresql-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgCbkfLWl9Ave1nPG0JlX4LHkeps32p2NztPVu+FD5Eqb6gIosXhNBZ+e01LVDY4nU1zD1+EZKqzP3CFB456PKCm6CV3GemfU1AYxvu/OzxkhdOlLCLg6jOriMtmO3L07PaF25nfS4NsGCbq1m29cnor+hgOv9ueHo4V4SZTe1QqofvEbz4u5ixsomj8fKUrXlobruqEUOXqAneEmeZdzYVyKqhg8HeM35zJG3MnQu+8vMlqmpVsx3mzgHOVCvrdchUzdCbYAW8yV9Guur27Qek/yQ7SByIllHze4jy7NXrNtTlpzELZ5rk4ka7fUl4Vaa6RzLZGgy0xp6TTl+FlCoCp84t8hvfhLp6Ykh7D4fOIkU2d2mUwkuXkDrvTXmpBbWHaVwtgPwwt56IxGgR9XHCVqdFMN+o0J8zR+REkty5vqkzz8ROAM5bhf7b07sjszHHD7zWiPfIB/n947qKWJWcbonsaVWnFCJPMS3ZiqbT2xv2yYLDqkGg/Ya6ITRReKOEiRnPSKAnyTqHAOSLEDm7ra+0ghU5kG+DyO6pDVabmncwPq6kSjRKuNk1wdlc1UIpAcc4hwy/sPkLSMZtxTCjs6jg4HWWRhIC1G99ktJjnhqk1hfMgtsKb2sUQlMTQCQpXTEmpLSISLcxYdLfR1FqO3DfxL8upRT2ooGkySoKkZDyUuBd9f/Wg3o4Fm7kL1oQRMf0xrKWf9wzaTeHTUCB3dI4VoTfQ9ozATl9TxCvWFQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-postgresql-password
      namespace: gitlab
