---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-initial-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgCeBmSE9XsVwJ4gXH/LUROqcZpkU6/aHeZojvJg9gqQId9AgnRaNcyK0iBcQbIxIfEIq8iPjDihOEC8oRkP7k9OE8ccbDESys4Fict06z/XTrYVtmOfJuTrHSFy7I2ROhUuH//ucRPBogZ/iYV5JBwLoipyc9xH6xV/kE3mZdiHTzLAl5EijdBub6lp4mxKqdvq4gRkq1HIgOLtShkapil8pfYE4txEjOTyCWVMT4eLeqnBIWDGAy4N0S0L5hvf7gnnBkcYd6l+CePt71hhBpMym60spYS3CgzQUkFREbhCT7AXeRll6a73+3131YNA5yypyUt3TGms3Kakkz0QLBMe6lYNbNQWfmpMInqyKLKLXtldYseTi5CwfqmfbcQc4vnPhL4vzVYldKlnQBxVFCYpstt2sGZ/fzxY+ESr8pYUiByYMC/4dU6Wj07wd2LNt80zu7gBzhYJw+iHHNN58ysEP+PfWz4k6lnU1gbnoY9vsvbxAVcm1/gmvFJw5sFMHZaYkxpYDrkagHm9w2xW4QmjhgwRsnCQVdkbROgmA2V0gVcbJiEVmn7o1wy3GxFxxdMXZdlIHNyFVoLJg586gGsaFGPJCSpDWTzDdAfq34x382Fdk7Oc+fI0QpklLMPfR7bPxgBRUi4gJCZZYApooHIT5iuVh1Ee8Q0duPUDfrGElxQLPnptnVlDIioW35zFNVFU4iq/cGW4qvTAq7WdyWMdHnr9u0jTwmXdcFPpbDahug==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-initial-root-password
      namespace: gitlab
