---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCMw2faR0VfbWhSpB2O8vvOudcewVoC+G+1lidmanQ2fygBTycCEJ2OrqTJyN/kXM2FDCABaJe/MGghKanRlhkzAiQ1p6xw1fv5aQ0d+NnUcHrRq7+VTS1tWMloNA5mamMlNe1zYj+Lt6vuemfFi88ABp377INJRNDeufIOwM7wt2kFV6OKjGFpxUBr+AXrp6CUc5LAq77VXj7H0fGNF6OoDzhuI2K/sK8dhHqVxzwNPIa9ypfNddLld9Sa2GwGCQCcyLiY0qyo8E0Mg6oLPWHMTDq8WLZxt+NNya5eygHwu7sanbtgqcZS7xBRB1jXIMmkp3zgETCJTK8FD8vy1tkzjqA58ucV8zqyjt8GVMJeCYDt0Z/uKfVjhzvPoe7zMLoc2bUrFBicZ1d2NAoYnjktrVKv4xzPcNIVgirRHNtNHCATib+dun8iBXC+ySHC0FxtOlzBewhBttRYHInUjnuuMT3yxJjT3y6FpKa9JF/soGwpZBaUaEWQkRitrVROx9HS7HvNm5V65UUYtaw8UCE21iXqIizwJGIhrWmn5cry56eAt9RH997/3yGRs2YrZuTkDo+eyIG+Dkilgu+3HziETwIF+JjG2Gtnm4gucgarw70ZFtwuzBVekyNfVoZcFLRsSRFlVcu0fEOdVAtTnqo26PcwmVpXEBlapOwFbN462wywH+sYijc+Vb8gL38ba4wYHJScQMD8eYa0LNfwmMpR/fo421XQ4cf0s6x640+s3g==
    admin-user: AgBAjzBlSw33GZOyq29l2yKoJNg67voDVKtAHDPVBnZlBpP1anUAwTZchloN+nEyyr2aWOJQhKcEGBXKHvqefQE3I87EJ5ujeYNfEuk46iEQgkhRAsugUryju9Fnht191ExtageVZYwCl89oa+gWcyS3gfcOGxVv9YZ/aCtOVRM7se3fYdMpLcRFXQ+kROrB0q++tDEYJnFVOeSwd1zYX84njzrMfvMvPM+GM/gN8fHIfEC8ayfeguoeKYmwcnYYvdt94pFh7rRX34XqCSOp9mhpnJcM7kqXA1quCzGEsspD+Qxanh7YUVjoQWl6InLdNrT/cMf0nX5zucDFjzNXghYQuItK3lfl/f2LUGnCkOW8CpMssMSMw3J/2wADShbync8B9GwREwpTvMXNGCE+YStvd2rJzIRyh9hhBtTGJ0Cnov5CSDsDuQbAW6Fse0vGFrXl78fDHb0QpdOc9EoXP/phCK/IkLnOYuTKrhDG0zDu4Cc1tgrwMsA4A06BuyfUb+T5ERlN5dKpMlnZxbE/+adNGbTBVr+uC2gCko6OwbJ3Cwu1xiLw55FLAEQAklb6nx/xNtNfyusDRmJQgL17O+vilvmfAfWV39vi299SEW8jln4H33r3WieIRRv2mU0lakst2v9yk4hRZj7eDZrGiH/Xqaor4i+ET7L3CF28er3Ezo1CIGFIqkVxHq2MSPosEJZmM0fzJg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
