# infrastructure/cloudflare/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare # Ensure this is deployed to the same namespace as the deployment
data:
  # config.yaml is the name of the file that will be mounted into the pod.
  config.yaml: |
    tunnel: e78bf68b-fc65-4c78-93e1-5a57f8cba852
    # The credentials file path within the container.
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: gitlab.blackcat.co.ke
        service: https://10.43.244.163:443
        originRequest:
          noTLSVerify: true
      - hostname: '*.apps.blackcat.co.ke' # A wildcard for other potential apps
        service: https://10.43.244.163:443
        originRequest:
          noTLSVerify: true
      # A catch-all to terminate any other requests as the final entry.
      - service: http_status:404
    # For k3s, the default CNI doesn't support network policies. If you add a CNI
    # that does, you might need to add a 'no-tls-verify' line here if you use
    # the default self-signed certs for internal traffic.