---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBQ+6aKqqnZEWdExSKdJ3u5NnfJ64TiLRAsBpoEkDggbiVokBOjwDRpUaJYivAoPHbUZbkfg5yQb2d2DV5FPBjkCb63t84u2EeZxAUvzc795tD2tDC6asKEA7LognUvjoTxl7n5wTVk5jli/7ClitVkY68QiFqvHliNp50Y57j0sMYk4H6/90dZHW6+R0E5YQyOlZqeRCi7qlTFfaaxGZvGw7i2AtUUSgntZ5tpgcqfbuaRhbhal4UK0jDxQcwqXQVkzxkxQsvLxAmEzOeFBPYiYD3OKH/17pI36KUhLs3/pGKRiqBtVqwCkEQR+LeBE1lFGF/M4QS7EhBv9Fg3Lf+RM9Ln6Jinsgtl63IsxgHV29A5RT0EWE9oKkCPxROIClIpQwcljrdmg0mbYnhS5YowfDaDeP4W9gX5HnAYdsTqD6FPHdr9b1MBizrSxipzZSUpozqhgJkakWeo49Ow2EcQC8MjBpbSEUlvxppA9z6dx7eGqKfqskm3TQyRy5XjcBdN1AKjkVJG6ZqVDRXu2AXGDk6EnjlSdGEpRfpRl3R3gwiZp4vL7MzKL/Tw50cNB9XJht4ZTKRyGvFKEzHFGQSaPq5kUPGCTXr/PGRg7fM4f3KB1rTID2FdoBOFkdT7CP/vp5gAZOVcDyMPz4ZeNNGuTdq+a0HB7feXZCXGaUvb6LAkETuUF9meSjrgrDmnYAtCRwVtmxToU9Vuq8oMfk5kq7deQm8pudJAabSMY/dfxfHF8e/2h2NSThRFGEE1YAhA9AnzqS3nXR/Y
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
