---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAf4FQI7HxBubCvanVqWEc9/IUH5oka8tGGtH6x5ZU+Do9WsCOnFn7dFhylaK3A+HN9BpWuly+c+5Lsu5DYAMZofv3vVjx6hoglKjVg1Xmin43DMEMDjUZ8A2aiv/SnGnEFzri9IZ4A0iDz9YU1WBEEBgRD/YIK//gt6o/hucP1edH5mOddtk111FezBqaNZC6nyAbhEPgFg8OONJ4OVK7b6avqUX4qLUpwq5agnWl34C4wU+MiTlcUGevbzW4eOdaKuJH6UesP2piOtwTiPvkeaJzbVnC3ChEwZmpErtU6hNNRI+4EeDUZyvaku3AlcSblfX84GvvQIt6M0pbk0bLp6a7rr5mtvlezyDTn2FLJi58yvgYcbdztKue7jelq4Houyi6QFIHBTl1p+EbmxWLlMoycc5XihRCGuJY2KEjQCRJ6aJ4wBs1bDan0oCS4MEOAAawvFoAzBEVLdMFlVIvdPeqVczToVhpZOtrcoEy5QSSgdF2mPFQCWSkramhkgOAuDSm6exyCavO0LBRSfNPnpn9vb/68dXqNGB2Po4WFOT4vjZS+mRqhiQywr0h1pU1QhlEfdcU66pw+4FpftSCZKZYGXzRsfIjI3mgfOSqum5cUQyT6hA37uoLqcmon8iLmSSlZqp9WTwZXZ3LP95qVTxapkIGqFK34ZIadKWHWRVVly8TIzo5Is8CCRqD+i1D3Uuvhxq8OZdO0oa20e6zILRoAw3OTWe5Vij0F2qyjSNy/aNXL7TI5lc/wtDGxQzShxss4OLLU9XoAh5Ii+ib7jC20vYXrTWRB2nuJdsv5u9LeNV4dYZFWjYKmEu2JOTWfSlYtN8LlYEB4GvD9wcd75enCdnW59xvInkHd2wOjtYcajCOrSQ8aBX82JGzG23fPGuOGkHxAilznoeNAy3uiJckyIaF4vUaQpfWsafW3
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
