---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCF9t97Hh3viEqlvCnLKFlpHyX+WFtEUhHfCysZn1kr/slEK7mQfxGL8dxQe00SJR2CCG0YXTTUblF9+BYMnSd00q76HG8wwDdgkoqqN/9q1mIuMP10Bqyl8ROv+1qp5qyiZwEsUJE94mVnQrQ+msBu+cyM5B3fhagOHLh6sH/eQcGUAAjOoQGSZ4NfjHrGTU8oVb0WLXtA5r/PkYIOBXjASIE0DKMU+i/MPrNXBB5vf/W9eyJy12Nx699H276cVpfEtIgpeGtNwSmkYg0wczczyVKV5EDVWX/7VOFfBfJXj1iplAYSo3F9n3MFFc3iKnyxgnF8G/j9UMUBymqeSyq0n8fjBUiBPKWeuaHl4ncWdmnSL6Ga0u0myDsCP648nRWxhoXJ3MY8XaChx2YHZZIzDsXI8Kal0hoS1RINn2Tfsm/G392qG0cel8jaTvwG1MG6deMiuYyVJqb7i9PZxZ+/Lr6tlMHjyY4ZGs/pYHdmVcJqOdUM5MKyRPNxbWBOmT7rrK2P3U4G4CUNPT0QCzHygoalz2u+Y120w9EgNSmu579e6xb0Cqn5/tQEpPBzLHQwWkKrv5t/CRRb0RUvZHE4mNoWLALfoolX9ee1kVAbQLoX7yb1udXNO4+BCKZUX1HirvQgmF7lXVGOvCTGP92wlJnGBUhlj1oJUpqxEgTpmYoR31Z1XY0U17jxUmz99zwZIarildp9+gza5VDoc0C6u74PAMSN4EdbbHlCBMHtk/3jEq+56Fvt0o7IcnHL6BwXvJFuZH8ZqzRy
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
