---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBpu4UsX6BXYCswOqvFfKS5r2eV5fnW7ro06S9+51dWDM7/A4BDcYpLAnnOHfl0a4nUrc/RwQw4hPm6zwtRC2Cs4IRhb8FgLIppwbceIs6kOWeiaKDGnZ1UPIsXM9yQQJypQxsXlj1uSltiORk/TfF81fyPM4lOx/6nhpEqpyWMEfvAioF9c2WYobA0fMEqNXvpgdT1ySPTTiWeGzq+A00C4AMaL5ZmnFnTHYsPkJf+FEectVQKc2p4X425PNombteezCXDZ1n4Fs7PzsUR4KyjXywDXmIqfS+p/2j/tHUVu0CKPBBzBLbODSsxAxe74rnjQ7jyhz7kRLZqT9iQH0JTNd/G6OeHTeGkqH/gflAXkRDyRKUM54xzI2LXXE9KzoVgl/i+I2XueEAH+PjeH99FVNWWCtCrjin5hD66pCQ8u32HC/hKNcqfaS80hqZS2QR/rZoHIiOY1+9upfIREMszQWbpcyK7Ojy0CiFa9GtQ8NTjAnRTwN67UrsH4wlVBXIjgrdZrrpxlEXMObaWx8h3diFsqQfZNnMNUNZsIp7Ev0EQzgwFPxpWVZVM/2MuSkJdA+y0bIPMzWnnONuXcQ2YGGo3dBTDDuxUIAOXT6uRLwxqctqkZOKvRJSGbQX70EhercRDZ5tA1P7KFLp3EHCiNxijfNAh4mg8s1veSESy9vd7vEPoaIc/GDLXpMQsEKYEhNFFrMjPhCwDKrBih1cCdqpmehpOtmI2hHLWRRN3maYMMAq4qQvVsrUBvZ6a2m0a5JVuWIj0rJn8Kmjqgvj8gzgbyQAM9aTFFYpy9vsquzZTtffpuVHmSMmxVXV14mCRVYqrs8c7UfYeUVApzGigGqu5RqCCI50ZJL1kTDpshRDVKcW5HfGYR+RkQ7H2wQFCt2+Rr+mu0ZVBCzQj/gR159+b9P343SITIeH31/zD
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
    type: Opaque
