# apps/forgejo-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    # We use the Forgejo Helm chart.
    repoURL: https://github.com/m0th3rch1p/gitlab.blackcat.git
    path: infrastructure/forgejo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true